blog/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

#Blog Post Form: Requires title and body
class BlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])
    submit = SubmitField("Post")

blog/blog_posts/views.py
from flask import render_template, request, url_for, flash, redirect, Blueprint
from flask_login import login_required, current_user
from blog import db
from blog.models import BlogPost
from blog.blog_posts.forms import BlogPostForm

blog_posts = Blueprint("blog_posts", __name__)

#Create Post Page: Validate and stores post information from form. Requires a logged in user
@login_required
@blog_posts.route("/create", methods=["GET", "POST"])
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post = BlogPost(user_id=current_user.id, title=form.title.data, body=form.body.data)

        db.session.add(blog_post)
        db.session.commit()

        flash("Post Successful")

        return redirect(url_for("core.index"))

    return render_template("create_post.html", form=form)

#Blog Post Page: Shows post matching id (int)
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    return render_template("blog_post.html", blog_post=blog_post)

#Update Post Page: Allows author to update post matching id (int). Requires a logged in user
@login_required
@blog_posts.route("/<int:blog_post_id>/update", methods=["GET", "POST"])
def update_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():
        blog_post.title = form.title.data
        blog_post.body = form.body.data

        db.session.commit()

        flash("Update Successful")

        return redirect(url_for("blog_posts.blog_post", blog_post_id=blog_post.id))

    elif request.method == "GET":
        form.title.data = blog_post.title
        form.body.data = blog_post.body

    return render_template("create_post.html", form=form)

#Delete Post Page: Allows author to delete post matching id (int). Requires a logged in user
@login_required
@blog_posts.route("/<int:blog_post_id>/delete", methods=["POST"])
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()

    flash("Delete Successful")

    return redirect(url_for("core.index"))

blog/core/views.py
from flask import render_template, request, Blueprint
from blog.models import BlogPost

core = Blueprint("core", __name__)

#Home Page: Maximum of 10 posts per page
@core.route("/")
def index():
    page = request.args.get("page", 1, type=int)

    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)

    return render_template("index.html", blog_posts=blog_posts)

#About Page
@core.route("/about")
def about():
    return render_template("about.html")

blog/users/views.py
from flask import render_template, request, url_for, flash, redirect, Blueprint
from flask_login import login_user, logout_user, login_required, current_user
from blog import db
from blog.models import User, BlogPost
from blog.users.forms import LoginForm, RegistrationForm, UpdateProfileForm
from blog.users.picture_handler import add_profile_picture

users = Blueprint("users", __name__)

#Login Page: Validates user information from form
@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:
            login_user(user)

            flash("Login Successful")

            return redirect(url_for("core.index"))

    return render_template("login.html", form=form)

#Registration Page: Validate and stores user information from form
@users.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()

        flash("Registration Successful")

        return redirect(url_for("users.login"))

    return render_template("register.html", form=form)

#Logout Page: Logs current user out
@users.route("/logout")
def logout():
    logout_user()

    return redirect(url_for("core.index"))

#Account Page: Shows user public information. Allows for updating of username and profile picture. Requires a logged in user
@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_profile = False

    form = UpdateProfileForm()

    if form.validate_on_submit():
        if form.username.data:
            current_user.username = form.username.data
            update_profile = True

        if form.userpicture.data:
            current_user.userpicture = add_profile_picture(current_user.username, form.userpicture.data)

            update_profile = True

        if update_profile:
            db.session.commit()

            flash("Update Successful")

        return redirect(url_for("users.account"))

    elif request.method == "GET":
        form.username.data = current_user.username

    userpicture = url_for("static", filename="profile_pictures/" + current_user.userpicture)

    return render_template("account.html", userpicture=userpicture, form=form)

#User Posts Page: Shows posts matching username (string). Maximum of 10 posts per page
@users.route("/<username>")
def user_posts(username):
    page = request.args.get("page", 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()

    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)

    return render_template("user_posts.html", blog_posts=blog_posts, user=user)

blog/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4 text-center">About</h1>
  <hr class="my-4">
  <p class="text-center">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

blog/templates/account.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">{{current_user.username}}'s Account</h1>
  <p></p>

  <img class="img-fluid mx-auto d-block" align="center" src="{{url_for("static", filename="profile_pictures/" + current_user.userpicture)}}">
  <hr class="my-4">

  <form action="" method="POST" enctype="multipart/form-data">
      {{form.hidden_tag()}}

      <div class="form-group">
        <label>Change Username</label>
        {{form.username(class="form-control", placeholder="Enter new username")}}
      </div>

      <div class="form-group">
        <label>Change Picture</label>
        {{form.userpicture(class="form-control-file")}}
      </div>

      {{form.submit(class="btn btn-primary")}}
  </form>
</div>
{% endblock %}

blog/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Micro Blog</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("core.index")}}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("core.about")}}">About</a>
            </li>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("blog_posts.create_post")}}">Create Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("users.account")}}">My Account</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("users.logout")}}">Logout</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("users.login")}}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for("users.register")}}">Register</a>
            </li>
          {% endif %}
        </div>
    </nav>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog_post.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">{{blog_post.title}}</h1>
  <h4 class="text-center">Written by: {{blog_post.author.username}}</h4>
  <h6 class="text-center">Published on: {{blog_post.date.strftime("%Y-%m-%d")}}</h6>

  <hr class="my-4">
  <p>{{blog_post.body}}</p>

  {% if blog_post.author == current_user %}
    <hr class="my-4">
    <a class="btn btn-primary" href={{url_for("blog_posts.update_post", blog_post_id=blog_post.id)}}>Update</a>
    <button type="button" class="btn btn-danger" name="Delete" data-toggle="modal" data-target="#delete_modal">Delete</button>
  {% endif %}
</div>

<div class="modal fade" tabindex="-1" role="dialog" aria-hidden="true" id="delete_modal" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this post?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for("blog_posts.delete_post", blog_post_id=blog_post.id)}}" method="POST">
          <input type="submit" class="btn btn-danger" name="" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">Create Post</h1>
  <hr class="my-4">

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        <label>Title</label>
        {{form.title(class="form-control", placeholder="Enter title")}}
      </div>

      <div class="form-group">
        <label>Text</label>
        {{form.body(class="form-control", rows = "6", placeholder="Enter text")}}
      </div>

      {{form.submit(class="btn btn-primary")}}
      </div>
  </form>
</div>
{% endblock %}

blog/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1 class="display-4 text-center">Micro Blog</h1>
  <p class="lead text-center">Login or register to create posts</p>
  <hr class="my-4">
  <p class="text-center">This micro blog was built by Jose Pereira as a training exercise for python & flask</p>
</div>

<div class="row">
  {% for blog_post in blog_posts.items %}
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">{{blog_post.title}}</h5>
        </div>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Published on: {{blog_post.date.strftime("%Y-%m-%d")}}</h6>
          <a href="{{url_for("users.user_posts", username=blog_post.author.username)}}" class="card-link">Written by: {{blog_post.author.username}}</a>
          <p></p>
          <a class="btn btn-primary btn-sm" href="{{url_for("blog_posts.blog_post", blog_post_id=blog_post.id)}}" class="btn btn-primary">Read Post</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<p></p>

<nav aria-label="Page Navigation">
  <ul class="pagination justify-content-center">
    {% for i in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if blog_posts.page == i %}
        <li class="page-item active"><a class="page-link" href="{{url_for("core.index", page=i)}}">{{i}}</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for("core.index", page=i)}}">{{i}}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>

{% endblock %}

blog/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">Login</h1>
  <hr class="my-4">

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        <label>Email address</label>
        {{form.email(class="form-control", placeholder="Enter email")}}
        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>

      <div class="form-group">
        <label>Password</label>
        {{form.password(class="form-control", placeholder="Enter password")}}
      </div>

      {{form.submit(class="btn btn-primary")}}
      </div>
  </form>
</div>
{% endblock %}

blog/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">Register</h1>
  <hr class="my-4">

  <form method="POST">
      {{form.hidden_tag()}}

      <div class="form-group">
        <label>Email address</label>
        {{form.email(class="form-control", placeholder="Enter email")}}
        <small class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>

      <div class="row">
        <div class="col">
          <label>Password</label>
          {{form.password(class="form-control", placeholder="Enter password")}}
        </div>
        <div class="col">
          <label>Confirm Password</label>
          {{form.password_confirm(class="form-control", placeholder="Re-Enter password")}}
        </div>
      </div>
      <p></p>

      {{form.submit(class="btn btn-primary")}}
      </div>
  </form>
</div>
{% endblock %}

blog/templates/user_posts.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <h1 class="display-4 text-center">{{current_user.username}}'s Blog Posts</h1>
  <p></p>

  <img class="img-fluid mx-auto d-block" align="center" src="{{url_for("static", filename="profile_pictures/" + current_user.userpicture)}}">
</div>

<div class="row">
  {% for blog_post in blog_posts.items %}
    <div class="col-sm-6">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title">{{blog_post.title}}</h5>
        </div>
        <div class="card-body">
          <h6 class="card-subtitle mb-2 text-muted">Published on: {{blog_post.date.strftime("%Y-%m-%d")}}</h6>
          <p></p>
          <a class="btn btn-primary btn-sm" href="{{url_for("blog_posts.blog_post", blog_post_id=blog_post.id)}}" class="btn btn-primary">Read Post</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<p></p>

<nav aria-label="Page Navigation">
  <ul class="pagination justify-content-center">
    {% for i in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if blog_posts.page == i %}
        <li class="page-item active"><a class="page-link" href="{{url_for("core.index", page=i)}}">{{i}}</a></li>
      {% else %}
        <li class="page-item disabled"><a class="page-link" href="{{url_for("core.index", page=i)}}">{{i}}</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}